{% set name = "oskar" %}

build:
  number: 0
  script_env:
    - VERSION

package:
  name: {{ name|lower }}
  version: {{ VERSION }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - casacore
  run:

about:
  home: https://github.com/OxfordSKA/OSKAR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SKA Radio Telescope Simulator'
  description: |
    The OSKAR package consists of a number of applications for the simulation of astronomical radio interferometers.
    OSKAR has been designed primarily to produce simulated data from telescopes that use aperture arrays, as envisaged for the SKA.
  doc_url: https://ska-telescope.gitlab.io/sim/oskar/
  dev_url: https://github.com/OxfordSKA/OSKAR

extra:
  recipe-maintainers:
    - Lukas Gehrig
